EATING_HEALTHY_DB_USERspring.application.name=workout-api

server.port=8081
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=eating_healthy_db;encrypt=true;trustServerCertificate=true
spring.datasource.username=${EATING_HEALTHY_DB_USER}
spring.datasource.password=${EATING_HEALTHY_DB_PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect